
CREATE TABLE IF NOT EXISTS `user` (
  `id` VARCHAR(191) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `password` VARCHAR(191) DEFAULT NULL,
  `role` ENUM('user', 'vendor', 'admin', 'driver') NOT NULL DEFAULT 'user',
  `name` VARCHAR(191) DEFAULT NULL,
  `phoneNumber` VARCHAR(191) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `city` VARCHAR(191) DEFAULT NULL,
  `state` VARCHAR(191) DEFAULT NULL,
  `zipCode` VARCHAR(191) DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_email_key` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `dispensary` (
  `id` VARCHAR(191) NOT NULL,
  `vendorId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `imageId` VARCHAR(191) DEFAULT NULL,
  `location` VARCHAR(191) DEFAULT NULL,
  `coordinates` JSON DEFAULT NULL,
  `rating` DOUBLE DEFAULT 0,
  `reviews` INT DEFAULT 0,
  `type` VARCHAR(191) DEFAULT NULL,
  `offers` JSON DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `suburb` VARCHAR(191) DEFAULT NULL,
  `city` VARCHAR(191) DEFAULT NULL,
  `state` VARCHAR(191) DEFAULT NULL,
  `zipCode` VARCHAR(191) DEFAULT NULL,
  `phone` VARCHAR(191) DEFAULT NULL,
  `website` VARCHAR(191) DEFAULT NULL,
  `hours` JSON DEFAULT NULL,
  `imageUrl` TEXT DEFAULT NULL,
  `categoryIds` JSON DEFAULT NULL,
  `isFeatured` BOOLEAN DEFAULT FALSE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `dispensary_slug_key` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product` (
  `id` VARCHAR(191) NOT NULL,
  `dispensaryId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `type` ENUM('Flower', 'Edible', 'Vape', 'Concentrate', 'Pre-roll', 'Soda') NOT NULL,
  `strain` ENUM('Indica', 'Sativa', 'Hybrid') DEFAULT NULL,
  `thc` DOUBLE DEFAULT NULL,
  `cbd` DOUBLE DEFAULT NULL,
  `price` DOUBLE DEFAULT NULL,
  `weight` VARCHAR(191) DEFAULT NULL,
  `pricing` JSON DEFAULT NULL,
  `ediblePricing` JSON DEFAULT NULL,
  `sodaPricing` JSON DEFAULT NULL,
  `imageId` VARCHAR(191) DEFAULT NULL,
  `imageUrl` TEXT DEFAULT NULL,
  `additionalImageUrls` JSON DEFAULT NULL,
  `stock` INT NOT NULL DEFAULT 0,
  `isFeatured` BOOLEAN DEFAULT FALSE,
  `isHotDeal` BOOLEAN DEFAULT FALSE,
  `salePrice` DOUBLE DEFAULT NULL,
  `effectsLength` VARCHAR(191) DEFAULT NULL,
  `benefits` TEXT DEFAULT NULL,
  `flavour` VARCHAR(191) DEFAULT NULL,
  `ingredients` TEXT DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `product_dispensaryId_idx` (`dispensaryId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `order` (
  `id` VARCHAR(191) NOT NULL,
  `dispensaryId` VARCHAR(191) NOT NULL,
  `customerId` VARCHAR(191) NOT NULL,
  `driverId` VARCHAR(191) DEFAULT NULL,
  `dispensaryName` VARCHAR(191) NOT NULL,
  `dispensaryState` VARCHAR(191) DEFAULT NULL,
  `customerName` VARCHAR(191) NOT NULL,
  `customerEmail` VARCHAR(191) NOT NULL,
  `items` JSON NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  `taxes` DOUBLE NOT NULL,
  `deliveryFee` DOUBLE NOT NULL,
  `commission` DOUBLE NOT NULL,
  `vendorPayout` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  `paymentMethod` VARCHAR(191) NOT NULL DEFAULT 'cash',
  `status` ENUM('pending', 'placed', 'confirmed', 'ready-for-pickup', 'out-for-delivery', 'completed', 'cancelled') NOT NULL DEFAULT 'placed',
  `address` TEXT NOT NULL,
  `city` VARCHAR(191) NOT NULL,
  `state` VARCHAR(191) NOT NULL,
  `zipCode` VARCHAR(191) NOT NULL,
  `confirmedAt` DATETIME(3) DEFAULT NULL,
  `pickedUpAt` DATETIME(3) DEFAULT NULL,
  `completedAt` DATETIME(3) DEFAULT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `order_dispensaryId_idx` (`dispensaryId`),
  KEY `order_customerId_idx` (`customerId`),
  KEY `order_driverId_idx` (`driverId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `driver` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `vehicleDetails` TEXT DEFAULT NULL,
  `availabilityStatus` ENUM('online', 'offline', 'on-delivery') NOT NULL DEFAULT 'offline',
  `city` VARCHAR(191) NOT NULL,
  `state` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `driver_userId_key` (`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
